import { Inter } from "next/font/google";
import "./globals.css";

// Configure Inter with weights and subsets
const inter = Inter({
  subsets: ["greek"],
  weight: ["400", "700"], // 400 for Regular, 700 for Bold
  variable: "--font-inter", // Optional: for custom CSS usage
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={``}
      >
        {children}
      </body>
    </html>
  );
}
